server:
  port: 8880
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/VEpardo/microPractice
          search-paths: config-data
  application:
    name: config-service
